services:
  kafka:
    image: apache/kafka:4.1.2
    container_name: kafka
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"